### ISSUE TITLE
Allows registration of proxy.i2p

### ISSUE THREAD

**Issue by marek22k** [wipedlifepotato/dns.chudo.i2p#1]
The domain proxy.i2p is reserved for the I2P router. The Java I2P version uses it, for example, in conjunction with the Addresshelper. Although the domain is reserved, dns.chudo.i2p allows this domain to be registered.

**Comment by wipedlifepotato** [comment]
Thanks. Have to be fixed in next commit.

If you know another reserved addresses then give me know, please.

ср, 14 июл. 2021 г., 21:49 Marek Küthe ***@***.***>:

**Comment by marek22k** [comment]
Well, b32.i2p and all subdomains of it.  b32.i2p is used to reach eepsites using their Base32.

**Comment by marek22k** [comment]
I just asked.  The following are also reserved:
router.i2p
console.i2p
*.proxy.i2p
*.router.i2p
*.console.i2p

**Comment by wipedlifepotato** [comment]
like to fixed in https://github.com/wipedlifepotato/dns.chudo.i2p/commit/a9e037bd52636dc270d33d797e6bb00a7a3107a3
